function [ LacI_vector, TetR_vector, nLacI_vector, nTetR_vector] = get_nullclines( inputs,p ,LacI_vector,TetR_vector)
%Greg: inputs are atc first and iptg second. was not the case before

    %hill_func = @(x,k,n) 1./(1+(x./k).^n);

    % varying IPTG and ATc inputs
    % IPTG = [1e6 3e6 5e6 8e6 1.1e7 2e7 3e7];
    % ATc = [2e6 4e6 6e6 9e6 2.4e7 3e7 4e7];
    % IPTG = [5e5 5e6 1.1e7 2e7 3e7 1e8];
    % ATc = [6e5 1.5e7 2.4e7 7e7 1e8 5e8];

    % Compute TetR nullcline:
    mRNAt = (p.crt ...
            + p.cit * hill_func(    LacI_vector * hill_func(    inputs(2), ...
                                                                p.kiptg, ...
                                                                p.miptg ...
                                                            ), ...
                                    p.k_l, ...
                                    p.nl ...
                                ) ...
            )...
            ./p.delta_mrnat;
    nTetR_vector = (p.ct.*mRNAt)./p.deltat;

    % Compute LacI nullcline:
    mRNAl = (p.crl ...
            + p.cil * hill_func(    TetR_vector * hill_func(    inputs(1), ...
                                                                p.katc, ...
                                                                p.matc ...
                                                            ), ...
                                    p.k_t, ...
                                    p.nt ...
                                )...
            ) ...
            ./p.delta_mrnal;
    nLacI_vector = (p.cl.*mRNAl)./p.deltal;


end

